### ISSUE TITLE
Allow multiple instances without changing namespace globally

### ISSUE THREAD

**Issue by ExplorersOdysseyDev** [ExplorersOdysseyGame/Game#5]
Line: 7
https://github.com/ExplorersOdysseyGame/Game/blob/d416fe14384ea078153d08b19a62bb33f45117cf//src/main/java/io/github/explorersodysseygame/game/common/Logger.java#L4-L14

**Comment by TJ20201** [comment]
Fixed with the patch where most classes were made non-static
